#! /bin/sh

# echo "host all  all  0.0.0.0/0  md5" >> /etc/postgresql/10.4/main/pg_hba.conf
# echo "listen_addresses='*'" >> /etc/postgresql/10.4/main/postgresql.conf

echo "host all  all  0.0.0.0/0  md5" >> /data/pg_hba.conf
# echo "listen_addresses='*'" >> /var/lib/postgresql/data/postgresql.conf
